KEEP-644/Video Embedding on Recommended Supplier
ordermentum/swift-sdk pull request #113
Opened 2021-03-04 01:17 UTC by jfabian06ph

#### Description

[Allow embedding a video in the supplier details page in Supplier Directory](https://ordermentum.atlassian.net/browse/KEEP-644)
----

2021-03-04 02:57 UTC, bstillitano requested changes

2021-03-04 02:57 UTC, bstillitano commented on OrdermentumSDK/Models/RecommendedSupplier.swift
> +    public var videoUrl: String = ""
Needs to be nullable

2021-03-04 03:47 UTC, jfabian06ph commented on OrdermentumSDK/Models/RecommendedSupplier.swift
> +    public var videoUrl: String = ""
Changes made

2021-03-05 05:00 UTC, bstillitano approved these changes

2021-03-05 05:00 UTC, merged