Story/RETAILER-3320/ New auth services
ordermentum/swift-sdk pull request #144
Opened 2021-09-02 10:22 UTC by mkmbayona

#### Description

https://ordermentum.atlassian.net/browse/RETAILER-3320

Add new auth services
Remove unused models

----
#### PR Type

_Check one or more and add the corresponding number of reviewers_

- [ ] Bugfix _(1)_
- [ ] Minor change _(1)_
- [ ] Refactor (no functional changes/no api changes) _(1)_
- [ ] Feature _(2)_
- [ ] Backwards compatible change in functionality _(2)_
- [ ] Breaking change (existing functionality no longer works as expected) _(2)_
- [ ] Critical impact (security, payments or critical functionality) _(2+CTO)_

----
#### Changes

_List the main changes in this PR. Include screenshots if necessary._

----

#### Acceptance Criteria

_How can we test that this meets the requirements of the ticket?_

----

#### Checklist:

- [ ] Tests – Have you added or edited the test cases?
- [ ] Context – Have you tested this with a non-admin user?
- [ ] Rebase – Has this PR been rebased against `develop`?
- [ ] Feature Flag - If this is a new feature, does it have a feature flag?
- [ ] Release - Can this be released to production once tested?

2021-09-02 12:42 UTC, bstillitano commented on Sources/OrdermentumSDK/Models/Auth.swift
> +    public init() {}
Can you move the init above the var definitions

2021-09-02 12:42 UTC, bstillitano commented on Sources/OrdermentumSDK/Models/Cart.swift
> -
Why does this PR touch the cart? Not sure we want to be deleting the cart here

2021-09-02 12:42 UTC, bstillitano commented on Sources/OrdermentumSDK/Models/Cart.swift
> -
Again, not sure why we're deleting this? Are they unused?

2021-09-02 12:43 UTC, bstillitano commented on Sources/OrdermentumSDK/Models/CodingKeys.swift
> +    case token_type
For these cases specifically, fine to leave as camel case as that's what the server epxects.

2021-09-02 12:45 UTC, bstillitano commented on Sources/OrdermentumSDK/Routers/AuthRouter.swift
> +            return try Client.instance.urlRequest(path: version+path, method: method, parameters: parameters, body: body)
Can avoid this by using `OM`. See `DocumentumService`

2021-09-02 12:46 UTC, bstillitano commented on Sources/OrdermentumSDK/Services/AuthService.swift
> +    public typealias AuthResponseCompletion = (Bool, AuthAccess?, ErrorResponse?) -> Void
Can we please remove this typealias. I understand the cleaniliness however it implies that all calls that relate to auth will always return this.

2021-09-02 12:46 UTC, bstillitano commented on Sources/OrdermentumSDK/Utilities/Config.swift
> +struct K {
What is `K`? What does it represent? We can't introduce a struct named `K` into the app.

2021-09-02 12:46 UTC, bstillitano commented on Sources/OrdermentumSDK/Utilities/Config.swift
> +        if let path = Bundle.main.path(forResource: K.mainConfig, ofType: "plist"), let dict = NSDictionary(contentsOfFile: path) as? [String: String] {
I don't see where you've introduce the plist file into the SDK?

2021-09-06 08:36 UTC, mkmbayona commented on Sources/OrdermentumSDK/Models/Cart.swift
> -
@bstillitano Just stumbled upon it and looks like it is not being used.

2021-09-06 08:37 UTC, mkmbayona commented on Sources/OrdermentumSDK/Models/Cart.swift
> -
@bstillitano Yeah just stumbled upon it and looks like it is not being used.

2021-09-06 08:38 UTC, mkmbayona commented on Sources/OrdermentumSDK/Models/Auth.swift
> +    }
@bstillitano Done

2021-09-06 08:51 UTC, mkmbayona commented on Sources/OrdermentumSDK/Clients/AuthClient.swift
> +    public var auth = AuthServiceV2()
@bstillitano We have an existing `AuthService`. Although I think we can put this into that class as the differences are all handled within the `AuthRouter`. You think this is a good time to transfer all of the auth stuff into the `OM` class?
Happy to discuss

2021-09-06 09:04 UTC, mkmbayona commented on Sources/OrdermentumSDK/Utilities/Config.swift
> +        if let path = Bundle.main.path(forResource: K.mainConfig, ofType: "plist"), let dict = NSDictionary(contentsOfFile: path) as? [String: String] {
@bstillitano The plist will actually be on the app. Goal was to somehow be similar to GoogleService-Info.plist for Firebase.
The SDK is a local one here but I've verified this works with the swift package using the repo url + specific branch:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/49466085/132189341-a4204c6f-b1b7-44e4-a07b-b3e949fa25a9.png">

2021-09-06 09:06 UTC, bstillitano commented on Sources/OrdermentumSDK/Clients/AuthClient.swift
> +    public var auth = AuthServiceV2()
Happy for you to migrate everything to OM.

2021-09-06 09:07 UTC, bstillitano commented on Sources/OrdermentumSDK/Models/Cart.swift
> -
Ok. So long as it's not being used it's fine to remove.

2021-09-07 01:28 UTC, bstillitano requested changes

2021-09-07 01:28 UTC, bstillitano commented on Sources/OrdermentumSDK/Models/Auth.swift
> +public struct AuthRequest: Codable {
All strcuts within the SDK must be initialisable without params. Please add a `public init() {}`

2021-09-07 01:28 UTC, bstillitano commented on Sources/OrdermentumSDK/Models/Auth.swift
> +public struct AuthRevoke: Codable {
All strcuts within the SDK must be initialisable without params. Please add a public init() {}

2021-09-07 01:28 UTC, bstillitano commented on Sources/OrdermentumSDK/Routers/AuthRouter.swift
> +        case .resetPassword,
As mentioned in an earlier review, please make these case by case. I understand that it's not best pracitce but in the context of the SDK, it make it easier to understand what we're hitting and also makes documentation a little nicer.

2021-09-09 23:54 UTC, bstillitano requested changes

2021-09-09 23:54 UTC, bstillitano commented on Sources/OrdermentumSDK/Services/AuthService.swift
> +    // MARK: - New auth services
Can we please remove this pragma.

2021-09-13 01:11 UTC, bstillitano commented on Sources/OrdermentumSDK/Utilities/Config.swift
> +struct Config {
Does this need to be a struct? Looks like all properties are calculated.

2021-09-13 04:15 UTC, merged