RETAILER-3761/ Supplier Notification Uplift
ordermentum/swift-sdk pull request #196
Opened 2022-03-22 04:17 UTC by jfabian06ph

#### Description

[iOS](https://ordermentum.atlassian.net/browse/RETAILER-3761)

----
#### PR Type

_Check one or more and add the corresponding number of reviewers_

- [ ] Bugfix _(1)_
- [ ] Minor change _(1)_
- [ ] Refactor (no functional changes/no api changes) _(1)_
- [ ] Feature _(2)_
- [ ] Backwards compatible change in functionality _(2)_
- [ ] Breaking change (existing functionality no longer works as expected) _(2)_
- [ ] Critical impact (security, payments or critical functionality) _(2+CTO)_

----
#### Changes

_List the main changes in this PR. Include screenshots if necessary._

----

#### Acceptance Criteria

_How can we test that this meets the requirements of the ticket?_

----

#### Checklist:

- [ ] Tests – Have you added or edited the test cases?
- [ ] Context – Have you tested this with a non-admin user?
- [ ] Rebase – Has this PR been rebased against `develop`?
- [ ] Feature Flag - If this is a new feature, does it have a feature flag?
- [ ] Release - Can this be released to production once tested?

2022-04-04 06:23 UTC, bstillitano commented on Sources/OrdermentumSDK/Services/NotificationsService.swift
> +    public func updateNotificationSetting(userId: String, supplierId: String, updateObject: [String: Bool]) async -> Result<Bool?, Error> {
Opporutnity to make this into an object?

2022-04-04 06:23 UTC, bstillitano requested changes
Isntead of passing around `[String: Bool]` is it possible to get notification settings into an object type?

2022-04-05 02:44 UTC, jfabian06ph commented on Sources/OrdermentumSDK/Services/NotificationsService.swift
> +    public func updateNotificationSetting(userId: String, supplierId: String, updateObject: [String: Bool]) async -> Result<Bool?, Error> {
change request made

2022-04-05 05:16 UTC, bstillitano approved these changes

2022-04-05 07:04 UTC, merged