KEEP329: Retailer Line Item Comments
ordermentum/swift-sdk pull request #98
Opened 2020-11-03 17:21 UTC by jfabian06ph

[iOS](https://ordermentum.atlassian.net/browse/KEEP-329)

2020-11-04 04:21 UTC, bstillitano approved these changes

2020-11-05 02:57 UTC, bstillitano requested changes

2020-11-05 02:57 UTC, bstillitano commented on OrdermentumSDK/Models/Cart.swift
> +    public var comment: String = ""
Please make this nullable.

2020-11-05 03:05 UTC, jfabian06ph commented on OrdermentumSDK/Models/Cart.swift
> +    public var comment: String = ""
Done

2020-11-05 05:09 UTC, merged